apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ecommerce-app

  template:
    metadata:
      labels:
        app: ecommerce-app

    spec:
      containers:
      - name: ecommerce-app

        image: zoya9545/cloudbridge-ecommerce:v1

        ports:
        - containerPort: 3000
